default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch('POSTGRES_USER') { 'postgres' } %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') { 'postgres' } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: RailsDeployTest_development

test:
  <<: *default
  host: <%= ENV.fetch('POSTGRES_HOST') { 'localhost' } %>
  database: RailsDeployTest_test

production:
  <<: *default
  database: RailsDeployTest_production
  username: RailsDeployTest
  password: <%= ENV['RAILSDEPLOYTEST_DATABASE_PASSWORD'] %>
